name: Build and Publish Gradle Plugin

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish to Gradle Plugin Portal
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: 'gradle'
        - name: Publish with Gradle
          env:
            GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
            GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          run: |
            ./gradlew build publishPlugins -Pgradle.publish.key=${GRADLE_PUBLISH_KEY} -Pgradle.publish.secret=${GRADLE_PUBLISH_SECRET}
